### ISSUE TITLE
Forkers: contacts always uploaded to iCloud even if haven't changed

### ISSUE THREAD

**Issue by malhal** [drewmccormack/Forked#13]
I noticed `Main fork has unmerged changes. Uploading...` being output on every launch and when ending an edit to a contact without making any changes.

I tracked it down to this attempted override of `==` :

https://github.com/drewmccormack/Forked/blob/daa1082ca0f8d4f5dc598be2887bdafcaf3e4c4b/Sources/Forked/Commit.swift#L32-L35

Not being called from:
https://github.com/drewmccormack/Forked/blob/daa1082ca0f8d4f5dc598be2887bdafcaf3e4c4b/Sources/ForkedCloudKit/CloudKitExchange.swift#L176

I believe you can't override `==` in a generic extension because it's static. There are some workarounds to convert it to dynamic however perhaps it would be better to just require that `Resource` is always `Equatable`?

This article has a couple of workarounds:
https://swiftunwrap.com/article/comparing-equatable-using-opened-existentials/

**Comment by drewmccormack** [comment]
Yeah, I think it would be better if at least CloudKitExchange requires it be Equatable. I actually thought that was already the case, but maybe it isn't.

What do you think? (Nice find by the way)

**Comment by malhal** [comment]
If that's possible then I suppose. The reason I thought to just make Resource conform to Equatable is I remembered Doug saying _every_ value type should:
https://youtu.be/A_b2oCBmm2Y?si=49u1M5USarVDsoXX&t=1114

**Comment by drewmccormack** [comment]
Yeah, it is hard to think of legit cases where it shouldn’t be equatable, and in the context of forked, it is very handy to be able to decide if one branch changed or the other. So I think requiring Equatable for Resource is indeed the right answer

**Comment by malhal** [comment]
edit: Think I was wrong about the below problem. Probably was a navigation issue.

Another problem is local edits do not update the UI correctly. I tracked it down to editingForker changes that are synced to displayedForkers does not cause the UI to update because SwiftUI does not think the `displayedForkers` array is different.
https://github.com/drewmccormack/Forked/blob/daa1082ca0f8d4f5dc598be2887bdafcaf3e4c4b/Samples/Forkers/Forkers/Models/Store.swift#L174-L187

I'll wait on Resource to become Equatable 😉

**Comment by drewmccormack** [comment]
I have now made Resource Equatable. Can you perhaps test this is now working?

**Comment by malhal** [comment]
Nice one, that seems to have resolved the issue. Also in Forkers it has fixed the main list not updating when making an edit.
