### ISSUE TITLE
Add model versioning for synced resources

### ISSUE THREAD

**Issue by drewmccormack** [drewmccormack/Forked#17]
Forked doesn't have any model versioning at the moment. Developers are free to handle versioning how they like. Most will likely adopt the Codable approach of only extending a model with optional properties. 

This approach is fine when Forked is just used on a single device. If there is a change to the model, the app automatically migrates the data, just like with `Codable`, and the new properties get `nil` values.

Things get more complicated when you want to sync across devices, because it is then possible that one device updates to the new model, and another doesn't. The device on the older model does not know about the new model, and could lose data. eg. You introduce a new optional property, and set it to a non-nil value. It syncs to a device with an old model, which doesn't recognize that property, and does not preserve its value.

This scenario is well known in sync frameworks, and a standard workaround is to store a model version, eg, simple Int, with the synced data. When the sync data arrives from another device, the model version is compared with the current model version in the app. If the data has a newer model version, it means it is from an unknown app version, and it is ignored. Usually the user would be told to upgrade the app at the same time. When the user does that, the sync will succeed.

For Forked, we should require conformance to a protocol for a model to sync. The protocol could be "VersionedModel". It would just have a single Int value for the struct, and a static Int for the current version (most recent). Classes like `CloudKitExchange` should require this.

`@ForkedModel` should support this via a parameter. Eg. `@ForkedModel(version: 2)`. This would be used to set the static current version. Code would also be injected into the merge method to check the model version if present, and throw if needed.

**Comment by Playrom** [comment]
I was exploring some ideas in my head, but I'm far from discussing them... but I think as well that this is a top priority 

The thing that I think it is necessary is to have an implementation that can fit all the uses cases, because someone in the future might try to implement a "SQLRepository" so we need to be careful to not have a simple solution that fits codable/cloudkit but not other kind of storage

I might expand on this concepts during the holidays, but I will not commit to it

**Comment by drewmccormack** [comment]
I've implemented the versioning as I laid out. Can certainly consider more sophisticated options down the track, so feel free to open an issue with a more advanced proposal.
