### ISSUE TITLE
Introduce ForkedFile

### ISSUE THREAD

**Issue by drewmccormack** [drewmccormack/Forked#8]
Currently, Forked only has the `AtomicRepository`, which is an in-memory repo that can also be serialized using `Codable`. 

For bigger files, eg images, it would probably be better to store the data for the forks on disk. A `FileRepository` should be written for this purpose. It would store contents in a directory, and have a subdirectory for each fork. The files themselves would go into the forks. A subdirectory may have one file, two files, or zero files, depending on the "occupation" of the fork.

This should be simple. Just conform to the `Repository` protocol, look at `AtomicRepository` for inspiration, and write the class. A few hours work at most, I would think. Good for someone who wants to start developing in Forked.

**Comment by nakul-py** [comment]
Hi @drewmccormack 
I came across this issue and would like to work on resolving it. Could you please assign it to me?

**Comment by drewmccormack** [comment]
It's all yours!
